### ISSUE TITLE
生成的长链接不能访问

### ISSUE THREAD

**Issue by Linstrong** [chenxuuu/Long-Link-Builder#1]
已经设置了伪静态，网站没有设置ssl，生成的长链接无法访问。还有就是怎么去掉下面的评论
http://www.loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.ooo

**Comment by chenxuuu** [comment]
https://github.com/chenxuuu/Long-Link-Builder/blob/f16b2e2c30ec09a5a12a9ef2df5e4a85e9eabfbe/str.php#L135

你这一行末尾是不是少了个斜杠？

**Comment by Linstrong** [comment]
> [长菱 - 建造/ str.php](https://github.com/chenxuuu/Long-Link-Builder/blob/f16b2e2c30ec09a5a12a9ef2df5e4a85e9eabfbe/str.php#L135)
> 
> [f16b2e2中的](/chenxuuu/Long-Link-Builder/commit/f16b2e2c30ec09a5a12a9ef2df5e4a85e9eabfbe) 第135 [行](/chenxuuu/Long-Link-Builder/commit/f16b2e2c30ec09a5a12a9ef2df5e4a85e9eabfbe)
> 
>  $ urlSite =“https://biubiubiubiubiubiubiubiubiubiubiubiubiubiubiubiubiubiubiubiubiubiu.com/”; 
> 你这一行末尾是不是少了个斜杠？

请问下面的评论部分可以去掉吗？

**Comment by chenxuuu** [comment]
@Linstrong 可以去掉啊。。
另外我也有过域名，叫yoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.ooo
不过不想续费了。。。

**Comment by Linstrong** [comment]
> @Linstrong可以去掉啊.. 
> 另外我也有过域名，叫yoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.ooo 
> 不过不想续费了...

e...其实我是想问你怎么去掉 >_<

**Comment by chenxuuu** [comment]
@Linstrong 删掉那两行就完事了
